### ISSUE TITLE
[Tracker] Token used before issued

### ISSUE THREAD

**Issue by vatsalparekh** [ansibleplaybookbundle/import-vm-apb#26] opened 2018-06-06 06:47 UTC
For few random times, I see the error `Token used before issued` for pvc
It might be a issue related to https://github.com/heketi/heketi/issues/646
But can we make sure anything from this apb point to avoid that?
it starts working fine once I delete the heketi pod (and it gets recreated)

**Comment by pkliczewski** [comment] 2018-06-06 09:24
@vatsalparekh Please provide logs where you see this issue.

**Comment by pkliczewski** [comment] 2018-06-06 11:30
Let's use this issue to track https://github.com/heketi/heketi/issues/646 and once it is fixed we can verify whether there is any need to push a PR to this repo.

**Comment by nellyc** [comment] 2018-07-24 12:39
@vatsalparekh can you still reproduce this issue?

**Comment by vatsalparekh** [comment] 2018-07-24 12:42
@nellyc I felt it was random for me, once it starts coming I see it happening till I delete the pod and let it create a new one, don't remember last when I saw this after filing this issue, but I did it few times after this

**Comment by nellyc** [comment] 2018-08-07 12:58
@vatsalparekh have you seen it since? if not we will close it as not able to reproduce

**Comment by vatsalparekh** [comment] 2018-08-07 13:00
@nellyc it is still quite random, I did face this last week

**Comment by grafuls** [comment] 2018-08-07 13:18
I have come across this issue as well last week. 
Not only importing VMs but also from `oc create` with VMI specs.

Not sure if relevant but on the gluster provisioner container log I could see this:
```
W0801 12:39:20.220785       1 reflector.go:341] github.com/kubernetes-incubator/external-storage/lib/controller/controller.go:498: watch of *v1.StorageClass ended with: The resourceVersion for the provided watch is too old.
W0801 12:45:55.715718       1 reflector.go:341] github.com/kubernetes-incubator/external-storage/lib/controller/controller.go:497: watch of *v1.PersistentVolume ended with: The resourceVersion for the provided watch is too old.
```

**Comment by KugelschreiberY** [comment] 2018-08-22 07:08
@grafuls I see the same log-messages as you in my gluster provisioner. Any updates?

**Comment by gageorsburn** [comment] 2018-09-17 16:12
Happening on 3.9. We had an issue that was previously fixed by setting `HEKETI_JWT_IAT_LEEWAY_SECONDS` to a value greater than 1. Killing the pod doesn't seem to fix the issue either.

```
[negroni] Started POST /volumes
[negroni] Completed 401 Unauthorized in 100.518µs
[negroni] Started POST /volumes
[negroni] Completed 401 Unauthorized in 106.238µs
[negroni] Started POST /volumes
[negroni] Completed 401 Unauthorized in 69.622µs
```

I can manually exec into the pod and create volume and it works just fine using the secret from environment variables passed in.

**Closed as not planned** 2022-08-25 14:42 UTC
Labels: bug
